server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: rms-analytics-system

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

cors:
  allowed-origins: "http://localhost:5000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

data:
  chunk-size: 10000
  dead-letter-path: ./data/dead_letter_queue/