server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: rms-analytics-system
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

cors:
  allowed-origins: "http://localhost:5000"

logging:
  level:
    com.ubereats.rms: DEBUG